services:
  db:
    image: postgres:17.6
    container_name: postgres_17_2money
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      # ./ означає поточну папку, де лежить docker-compose.yml
      - ./pg_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:7.2-alpine
  #   container_name: redis-oss
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis_data:/data
  #   # Увімкнення режиму AOF (Append Only File) для надійного збереження даних
  #   command: redis-server --appendonly yes

  # valkey:
  #   image: valkey/valkey:7.2-alpine
  #   container_name: valkey-oss
  #   restart: unless-stopped
  #   ports:
  #     # Прокидаємо порт зі змінної оточення (за замовчуванням 6379)
  #     - "${REDIS_PORT:-6379}:6379"
  #   volumes:
  #     # Рекомендую перейменувати папку для даних, щоб не плутати з redis
  #     - ./valkey_data:/data
  #   # Запуск сервера Valkey з AOF та встановленням пароля
  #   command: valkey-server --appendonly yes --requirepass "${REDIS_PASSWORD}"